version: '3.7'

services:
  my-backend:
    image: asia.gcr.io/team-project-dabae/dabae:0.9
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
