version: '3.7'

services:
  my-backend:
    image: asia.gcr.io/omega-research-357204/dabae:2.2
    platform: linux/x86_64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
